sudo: required
services:
  - docker

before_install:
  - docker build -t dhaxor/docker-frontend -f Dockerfile.dev .

script:
  - travis_wait 30 docker run dhaxor/docker-frontend yarn run test -- --coverage