sudo: required
YARN_GPG: no
services:
  - docker

before_install:
  - docker build -t dhaxor/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true dhaxor/docker-frontend yarn run test

deploy:
  provider: elasticbeanstalk
  region: "af-south-1"
  app: "frontend-docker"
  env: "Frontenddocker-env"
  bucket_name: "elasticbeanstalk-af-south-1-531095638142"
  bucket_path: "frontend-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY" 
