sudo: required
YARN_GPG: no
services:
  - docker

before_install:
  - docker build -t dhaxor/docker-frontend -f Dockerfile.dev .

script:
  - docker run dhaxor/docker-frontend yarn run test -- --coverage
 
